#!/usr/bin/env python3
"""
Regenerate ps7_prism_config.tcl from the Prism reference XSA.

    ./gen_ps7_config.py <prism_lcctrl.xsa> > ps7_prism_config.tcl

The running PetaLinux image was configured by an FSBL built from this XSA, so
the PS7 in any bitstream we load at runtime must agree with it (DDR, MIO, PLLs
and the FCLK sources).  Rather than retype 265 PCW_* values by hand, lift them
out of the XSA's block design.  PCW_ACT_* are Vivado-derived "actual" values
and are read-only, so they are skipped.
"""
import json
import sys
import zipfile

BD = "prj/prismtoo.srcs/sources_1/bd/design_1/design_1.bd"

with zipfile.ZipFile(sys.argv[1]) as z:
    bd = json.loads(z.read(BD))

params = bd["design"]["components"]["processing_system7_0"]["parameters"]

print("# GENERATED by gen_ps7_config.py from %s - do not edit by hand." % sys.argv[1].split("/")[-1])
print("# PS7 configuration of the Prism board, as used by its FSBL / PetaLinux.")
print("set PRISM_PS7_CONFIG [dict create \\")
for k in sorted(params):
    if k.startswith("PCW_ACT_"):
        continue
    v = params[k]["value"] if isinstance(params[k], dict) else params[k]
    # The .bd serialiser splits long strings into a list at spaces
    # ("... SD 0#..." -> [..."SD", "0#..."]); join them back.
    if isinstance(v, list):
        v = " ".join(v)
    print("    CONFIG.%s {%s} \\" % (k, v))
print("]")
