# ---------------------------------------------------------------------------
# Prism console - LCD source-synchronous output timing
#
# 832 x 500 @ 25.000 MHz = 60.1 Hz  ->  40.000 ns pixel clock.
#
# Setup and hold come from the ST7262 datasheet section 9.3.4 (System Bus
# Timing for RGB Interface), which specifies 12 ns minimum for EVERY input:
#   Tdsu / Tdhd    data setup / hold      12 ns min
#   Tdest / Tdehd  DE setup / hold        12 ns min
#   Thst / Thhd    HSYNC setup / hold     12 ns min
#   Tvst / Tvhd    VSYNC setup / hold     12 ns min
# The CH500WV05A-T module datasheet draws these symbols but gives no values;
# the driver IC datasheet does, so use its numbers.
#
# DCLK is forwarded 180 degrees out of phase, so there is ~20 ns of margin on
# each side against the 12 ns requirement.
# ---------------------------------------------------------------------------

create_clock -period 40.000 -name pix_clk [get_ports clk]

# The forwarded DCLK is generated by the ODDR inside lcd_clock_out,
# non-inverted to match the default i_clk_invert = 0.  The panel latches on
# the FALLING edge (measured), hence -clock_fall on the output delays.
create_generated_clock -name lcd_dclk \
    -source [get_pins u_lcd/u_clk_out/u_oddr/C] \
    -divide_by 1 \
    [get_ports o_clk]

# ST7262 9.3.4: 12 ns min setup and hold on data, DE, HSYNC and VSYNC alike.
set LCD_TSU 12.000
set LCD_THD 12.000

set lcd_data_ports [get_ports {o_red[*] o_green[*] o_blue[*] o_de o_hsync o_vsync}]

set_output_delay -clock lcd_dclk -clock_fall -max  $LCD_TSU $lcd_data_ports
set_output_delay -clock lcd_dclk -clock_fall -min [expr {-1 * $LCD_THD}] $lcd_data_ports

# DISP and the backlight enable change at most once per power sequence and
# have no setup requirement relative to DCLK; the ST7262 specifies them only
# in milliseconds (section 11).
set_false_path -to [get_ports {o_disp o_bl_en}]
