# ---------------------------------------------------------------------------
# Prism console - LCD source-synchronous output timing
#
# 1056 x 525 @ 60 Hz -> 33.264 MHz -> 30.0625 ns.
#
# CAVEAT: the CH500WV05A-T datasheet draws tdsu / tdhd on its "Input Clock and
# Data Timing Diagram" but gives NO numeric values for them anywhere in the
# document (its timing table only covers Fclk, Tclk, duty and the internal
# gate-driver delays).  The 8 ns / 8 ns used below is a conservative figure
# typical of this panel class, NOT a datasheet number.  With the ODDR
# forwarding a 180-degree clock there is ~15 ns of margin either side, so
# there is plenty of room even if the real numbers are worse.
# ---------------------------------------------------------------------------

create_clock -period 30.062 -name pix_clk [get_ports clk]

# The forwarded DCLK is generated by the ODDR inside lcd_clock_out, inverted
# with respect to the internal pixel clock.
create_generated_clock -name lcd_dclk \
    -source [get_pins u_lcd/u_clk_out/u_oddr/C] \
    -divide_by 1 -invert \
    [get_ports o_clk]

set LCD_TSU 8.000
set LCD_THD 8.000

set lcd_data_ports [get_ports {o_red[*] o_green[*] o_blue[*] o_de o_hsync o_vsync}]

set_output_delay -clock lcd_dclk -max  $LCD_TSU $lcd_data_ports
set_output_delay -clock lcd_dclk -min [expr {-1 * $LCD_THD}] $lcd_data_ports

# DISP and the backlight enable are static-ish control signals: they change at
# most once per power sequence and the panel has no setup requirement on them.
set_false_path -to [get_ports {o_disp o_bl_en}]
