# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/axis_switch_1/axis_switch_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_switch_1 || ORIG_REF_NAME==axis_switch_1} -quiet] -quiet

# IP: ip/axis_broadcaster_0/axis_broadcaster_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_broadcaster_0 || ORIG_REF_NAME==axis_broadcaster_0} -quiet] -quiet

# IP: ip/axis_switch_0/axis_switch_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_switch_0 || ORIG_REF_NAME==axis_switch_0} -quiet] -quiet

# IP: ip/axis_broadcaster_1/axis_broadcaster_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_broadcaster_1 || ORIG_REF_NAME==axis_broadcaster_1} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_repeater_0_0/design_1_repeater_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_repeater_0_0 || ORIG_REF_NAME==design_1_repeater_0_0} -quiet] -quiet

# IP: ip/axis_switch_1/axis_switch_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_switch_1 || ORIG_REF_NAME==axis_switch_1} -quiet] -quiet

# IP: ip/axis_broadcaster_0/axis_broadcaster_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_broadcaster_0 || ORIG_REF_NAME==axis_broadcaster_0} -quiet] -quiet

# IP: ip/axis_switch_0/axis_switch_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_switch_0 || ORIG_REF_NAME==axis_switch_0} -quiet] -quiet

# IP: ip/axis_broadcaster_1/axis_broadcaster_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_broadcaster_1 || ORIG_REF_NAME==axis_broadcaster_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_1/design_1_smartconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_1 || ORIG_REF_NAME==design_1_smartconnect_0_1} -quiet] -quiet

# Block Designs: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/bd_886d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_0/bd_886d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_1/bd_886d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_2/bd_886d_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_3/bd_886d_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_4/bd_886d_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_5/bd_886d_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_6/bd_886d_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_7/bd_886d_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_8/bd_886d_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_9/bd_886d_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_10/bd_886d_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_11/bd_886d_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_12/bd_886d_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_13/bd_886d_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_14/bd_886d_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_15/bd_886d_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_16/bd_886d_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_17/bd_886d_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_18/bd_886d_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_19/bd_886d_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_20/bd_886d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_21/bd_886d_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_22/bd_886d_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_23/bd_886d_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_24/bd_886d_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_25/bd_886d_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_26/bd_886d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_2/design_1_smartconnect_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_2 || ORIG_REF_NAME==design_1_smartconnect_0_2} -quiet] -quiet

# Block Designs: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/bd_892d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_0/bd_892d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_1/bd_892d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_2/bd_892d_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_3/bd_892d_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_4/bd_892d_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_5/bd_892d_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_6/bd_892d_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_7/bd_892d_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_8/bd_892d_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_9/bd_892d_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_10/bd_892d_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_11/bd_892d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_12/bd_892d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/ip/axis_switch_1/axis_switch_1_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/ip/axis_broadcaster_0/axis_broadcaster_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/ip/axis_switch_0/axis_switch_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/ip/axis_broadcaster_1/axis_broadcaster_1_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/ip/axis_switch_1/axis_switch_1_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/ip/axis_broadcaster_0/axis_broadcaster_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/ip/axis_switch_0/axis_switch_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/ip/axis_broadcaster_1/axis_broadcaster_1_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_1/bd_886d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_1/bd_886d_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_2/bd_886d_arsw_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_3/bd_886d_rsw_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_4/bd_886d_awsw_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_5/bd_886d_wsw_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_6/bd_886d_bsw_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_10/bd_886d_s00a2s_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_11/bd_886d_sarn_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_12/bd_886d_srn_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_16/bd_886d_s01a2s_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_17/bd_886d_sawn_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_18/bd_886d_swn_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_19/bd_886d_sbn_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_20/bd_886d_m00s2a_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_21/bd_886d_m00arn_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_22/bd_886d_m00rn_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_23/bd_886d_m00awn_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_24/bd_886d_m00wn_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_25/bd_886d_m00bn_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_1/bd_892d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_1/bd_892d_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_5/bd_892d_s00a2s_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_6/bd_892d_sarn_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_7/bd_892d_srn_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_8/bd_892d_sawn_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_9/bd_892d_swn_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_10/bd_892d_sbn_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_11/bd_892d_m00s2a_0_ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/ooc.xdc

# XDC: c:/Users/srikr/Documents/prism-hw-main/testAll/testAll.gen/sources_1/bd/design_1/design_1_ooc.xdc
